### PR TITLE
Initial implementation of credentials retrieval and DRAC reboot command

### PR DESCRIPTION
**Pull request by robertodauria**
This PR includes an initial implementation of:
- drac package: wraps the SSH connection to a DRAC and includes some basic unit tests. To allow testing, the dependency on the `ssh` module is abstracted and replaced with mock objects in the tests. The only feature that's implemented at the moment is the reboot command.
- datastore: retrieves host, username and password for a DRAC from Google Cloud Datastore
- main: starts an HTTP server implementing the `/reboot?host=<hostname>` endpoint

Please note that this is not meant as a complete implementation and test coverage isn't extensive as well, but since the diff is getting quite big (indicatively, I would like to keep PRs within 200 lines) I thought it might be easier to start reviewing it while we implement the missing parts.

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/reboot-service/1)

### CODE REVIEW

**Review by stephen-soltesz — CHANGES_REQUESTED** [review]
I agree that ~200 lines is the sweet spot for PRs. In this case, because we're introducing a new project and to start out on the best foot, please remove all but the drac package from this PR, and include a minimal .travis.yml config that runs the unit tests and adds coverage support.

Then subsequent PRs can build on the drac interface. I've added some comments on the other files, but you can address those in later changes. How does it sound?

> *[Reviewable](https://reviewable.io/reviews/m-lab/reboot-service/1#-:-LZGIvbm6r0pi5C4PiVw:b-qnmycl)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @evfirerob and @stephen-soltesz)

___
*[datastore.go, line 29 at r1](https://reviewable.io/reviews/m-lab/reboot-service/1#-LZGUg5a3lgk0sKWh7KK:-LZGUg5a3lgk0sKWh7KL:b-dos01l) ([raw file](https://github.com/m-lab/reboot-service/blob/28a3e2a37825970b92b90ddd50107d50a4cf922c/datastore.go#L29)):*
> ```Go
> 	ctx := context.Background()
> 
> 	client, err := datastore.NewClient(ctx, projectID)
> ```

How will we specify alternate projects?
___
*[main.go, line 40 at r1](https://reviewable.io/reviews/m-lab/reboot-service/1#-LZGJPq67ZFZpT4fpC8Z:-LZGJPq67ZFZpT4fpC8_:b-vr471d) ([raw file](https://github.com/m-lab/reboot-service/blob/28a3e2a37825970b92b90ddd50107d50a4cf922c/main.go#L40)):*
> ```Go
> 	}
> 
> 	conn, err := drac.NewConnection(host, defaultDRACPort, username, password, fPrivateKeyPath)
> ```

The hostname, username, and password are part of the Datastore model. Could / should the drac port also be there?

Something feels funny about having three sources of information currently: user providing hostname, const providing port, and datastore providing credentials. I can also imagine the user providing a "host:port" string. For example, the https://golang.org/pkg/net/http/ package accepts pre-formatted "host:port" strings for listening. 
___
*[main.go, line 57 at r1](https://reviewable.io/reviews/m-lab/reboot-service/1#-LZGKhbL4nXrXECjZ0cC:-LZGKhbL4nXrXECjZ0cD:b-si7rd5) ([raw file](https://github.com/m-lab/reboot-service/blob/28a3e2a37825970b92b90ddd50107d50a4cf922c/main.go#L57)):*
> ```Go
> // RebootHandler is the GET handler for /reboot
> func RebootHandler(w http.ResponseWriter, r *http.Request) {
> 	if r.Method != http.MethodGet {
> ```

Because this is a state changing operation, I suggest not using GET. A POST or other method would be more suitable. https://en.wikipedia.org/wiki/Representational_state_transfer
___
*[main.go, line 62 at r1](https://reviewable.io/reviews/m-lab/reboot-service/1#-LZGMF5AE__xbXuTIXnE:-LZGMF5AE__xbXuTIXnF:b-ovd4zh) ([raw file](https://github.com/m-lab/reboot-service/blob/28a3e2a37825970b92b90ddd50107d50a4cf922c/main.go#L62)):*
> ```Go
> 	}
> 
> 	hosts, ok := r.URL.Query()["host"]
> ```

`r.URL.Query().Get("host")`?
___
*[README.md, line 5 at r1](https://reviewable.io/reviews/m-lab/reboot-service/1#-LZGQfmI33bFlEu_iaM2:-LZGQfmI33bFlEu_iaM3:b-dm4arm) ([raw file](https://github.com/m-lab/reboot-service/blob/28a3e2a37825970b92b90ddd50107d50a4cf922c/README.md#L5)):*
> ```Markdown
> DRACs.
> 
> It retrieves login credentials from Google Cloud Datastore, which replaces PLC
> ```

Let's not even mention PLC in our new service.
___
*[README.md, line 15 at r1](https://reviewable.io/reviews/m-lab/reboot-service/1#-LZGR5in1N26g5c6BkKC:-LZGR5in1N26g5c6BkKD:banoo2m) ([raw file](https://github.com/m-lab/reboot-service/blob/28a3e2a37825970b92b90ddd50107d50a4cf922c/README.md#L15)):*
> ```Markdown
>     
> ### Things that do *NOT* work yet:
> - Authentication to Datastore with custom application credentials
> ```

You know about the `GOOGLE_APPLICATION_CREDENTIALS` env variable? It should be sufficient to point that at a suitable service account key file. So, you may not need to change any code to support this.
___
*[drac/drac.go, line 100 at r1](https://reviewable.io/reviews/m-lab/reboot-service/1#-LZGGJZpBXf8tHvSJ98f:-LZGGJZpBXf8tHvSJ98g:bkbdk8u) ([raw file](https://github.com/m-lab/reboot-service/blob/28a3e2a37825970b92b90ddd50107d50a4cf922c/drac/drac.go#L100)):*
> ```Go
> }
> 
> func (c *DRACConnection) getSession(client Client) (*ssh.Session, error) {
> ```

This method does not use any of the fields in `c`. Does it need to be a method (instead of a function)?
___
*[drac/drac.go, line 122 at r1](https://reviewable.io/reviews/m-lab/reboot-service/1#-LZGGxdzAujUjVBi4sT3:-LZGGxdzAujUjVBi4sT4:b-rl405j) ([raw file](https://github.com/m-lab/reboot-service/blob/28a3e2a37825970b92b90ddd50107d50a4cf922c/drac/drac.go#L122)):*
> ```Go
> 
> 	if err != nil {
> 		log.Fatalf("Command execution failed: %s\n", err)
> ```

log.Fatal exits. Why not return the error here?
___
*[drac/drac.go, line 127 at r1](https://reviewable.io/reviews/m-lab/reboot-service/1#-LZGIIajBE_wNMuBYiHe:-LZGIIajBE_wNMuBYiHf:bb6kdff) ([raw file](https://github.com/m-lab/reboot-service/blob/28a3e2a37825970b92b90ddd50107d50a4cf922c/drac/drac.go#L127)):*
> ```Go
> 	defer session.Close()
> 
> 	out, _ := session.CombinedOutput(cmd)
> ```

Please check all errors.
___
*[drac/drac_test.go, line 1 at r1](https://reviewable.io/reviews/m-lab/reboot-service/1#-LZGRp6GD0QWL35WWVRk:-LZGRp6GD0QWL35WWVRl:b4p4tyw) ([raw file](https://github.com/m-lab/reboot-service/blob/28a3e2a37825970b92b90ddd50107d50a4cf922c/drac/drac_test.go#L1)):*
> ```Go
> // Package drac contains the functions to establish an SSH connection with
> ```

No need to repeat the docstring in the test file.
___
*[drac/drac_test.go, line 45 at r1](https://reviewable.io/reviews/m-lab/reboot-service/1#-LZGT1fcE8zQYmoaJR5M:-LZGT1fcE8zQYmoaJR5N:bwhauqh) ([raw file](https://github.com/m-lab/reboot-service/blob/28a3e2a37825970b92b90ddd50107d50a4cf922c/drac/drac_test.go#L45)):*
> ```Go
> 
> func TestNewConnection(t *testing.T) {
> 	_, err := os.Create(privateKeyPath)
> ```

Is this needed?
___
*[drac/drac_test.go, line 65 at r1](https://reviewable.io/reviews/m-lab/reboot-service/1#-LZGTp9M1voOkD3oyEvy:-LZGTp9M1voOkD3oyEvz:besh2ix) ([raw file](https://github.com/m-lab/reboot-service/blob/28a3e2a37825970b92b90ddd50107d50a4cf922c/drac/drac_test.go#L65)):*
> ```Go
> }
> 
> func TestDRACConnection_connect(t *testing.T) {
> ```

Prefer testing public interfaces whenever possible.

In this case, we could make Connect public, or only test Exec after wrapping `*ssh.Session` in an interface.

**Review by robertodauria — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/reboot-service/1)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @evfirerob and @stephen-soltesz)

___
*[README.md, line 5 at r1](https://reviewable.io/reviews/m-lab/reboot-service/1#-LZGQfmI33bFlEu_iaM2:-LZJsDMd2MzOADqh_m2n:b-896fix) ([raw file](https://github.com/m-lab/reboot-service/blob/28a3e2a37825970b92b90ddd50107d50a4cf922c/README.md#L5)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Let's not even mention PLC in our new service.
</blockquote></details>

Done.
___
*[README.md, line 15 at r1](https://reviewable.io/reviews/m-lab/reboot-service/1#-LZGR5in1N26g5c6BkKC:-LZJsDuUAMqGexdv6bfo:bu7xgvi) ([raw file](https://github.com/m-lab/reboot-service/blob/28a3e2a37825970b92b90ddd50107d50a4cf922c/README.md#L15)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

You know about the `GOOGLE_APPLICATION_CREDENTIALS` env variable? It should be sufficient to point that at a suitable service account key file. So, you may not need to change any code to support this.
</blockquote></details>

Done. I've referenced this variable in the README.md. 
___
*[drac/drac.go, line 100 at r1](https://reviewable.io/reviews/m-lab/reboot-service/1#-LZGGJZpBXf8tHvSJ98f:-LZJsJBV-5wsh4089ab7:b-sk8jd1) ([raw file](https://github.com/m-lab/reboot-service/blob/28a3e2a37825970b92b90ddd50107d50a4cf922c/drac/drac.go#L100)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

This method does not use any of the fields in `c`. Does it need to be a method (instead of a function)?
</blockquote></details>

Done, I made it a function.
___
*[drac/drac.go, line 122 at r1](https://reviewable.io/reviews/m-lab/reboot-service/1#-LZGGxdzAujUjVBi4sT3:-LZJsNq13lrrVZlvXphp:b-896fix) ([raw file](https://github.com/m-lab/reboot-service/blob/28a3e2a37825970b92b90ddd50107d50a4cf922c/drac/drac.go#L122)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

log.Fatal exits. Why not return the error here?
</blockquote></details>

Done.
___
*[drac/drac.go, line 127 at r1](https://reviewable.io/reviews/m-lab/reboot-service/1#-LZGIIajBE_wNMuBYiHe:-LZJsPQ2Aung5KKYNwFH:b-896fix) ([raw file](https://github.com/m-lab/reboot-service/blob/28a3e2a37825970b92b90ddd50107d50a4cf922c/drac/drac.go#L127)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Please check all errors.
</blockquote></details>

Done.
___
*[drac/drac_test.go, line 1 at r1](https://reviewable.io/reviews/m-lab/reboot-service/1#-LZGRp6GD0QWL35WWVRk:-LZJsQcL-Ju7gVo3JNhY:b-896fix) ([raw file](https://github.com/m-lab/reboot-service/blob/28a3e2a37825970b92b90ddd50107d50a4cf922c/drac/drac_test.go#L1)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

No need to repeat the docstring in the test file.
</blockquote></details>

Done.
___
*[drac/drac_test.go, line 45 at r1](https://reviewable.io/reviews/m-lab/reboot-service/1#-LZGT1fcE8zQYmoaJR5M:-LZJsUIaBKcGaCRQmRRG:bfj0vzu) ([raw file](https://github.com/m-lab/reboot-service/blob/28a3e2a37825970b92b90ddd50107d50a4cf922c/drac/drac_test.go#L45)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Is this needed?
</blockquote></details>

Done. Short answer is: no.

Slightly longer answer is: not for now. The `drac` module aims to support private key authentication, even if we are still not using it on DRACs. That file creation allowed me to test a code path that maybe can be directly removed from this PR, and re-added later. 
___
*[main.go, line 40 at r1](https://reviewable.io/reviews/m-lab/reboot-service/1#-LZGJPq67ZFZpT4fpC8Z:-LZJtWS55Qw0L8YBpF7e:bc91vvy) ([raw file](https://github.com/m-lab/reboot-service/blob/28a3e2a37825970b92b90ddd50107d50a4cf922c/main.go#L40)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

The hostname, username, and password are part of the Datastore model. Could / should the drac port also be there?

Something feels funny about having three sources of information currently: user providing hostname, const providing port, and datastore providing credentials. I can also imagine the user providing a "host:port" string. For example, the https://golang.org/pkg/net/http/ package accepts pre-formatted "host:port" strings for listening. 
</blockquote></details>

I agree, the datastore should also contain the port. We will always have two sources, as the user needs to specify the host to work on, and everything else can be retrieved from Datastore. I've removed main.go and datastore.go from this PR but will add them back later and implement this suggestion.
___
*[main.go, line 57 at r1](https://reviewable.io/reviews/m-lab/reboot-service/1#-LZGKhbL4nXrXECjZ0cC:-LZJtytA7UyEIGr3bDf6:b-mrj0kn) ([raw file](https://github.com/m-lab/reboot-service/blob/28a3e2a37825970b92b90ddd50107d50a4cf922c/main.go#L57)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Because this is a state changing operation, I suggest not using GET. A POST or other method would be more suitable. https://en.wikipedia.org/wiki/Representational_state_transfer
</blockquote></details>

Definitely. As above, will implement this change in a subsequent PR.

**Review by robertodauria — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/reboot-service/1)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @evfirerob and @stephen-soltesz)

___
*[drac/drac_test.go, line 65 at r1](https://reviewable.io/reviews/m-lab/reboot-service/1#-LZGTp9M1voOkD3oyEvy:-LZ_88pyEG5j6sdkb0y8:baby5zn) ([raw file](https://github.com/m-lab/reboot-service/blob/28a3e2a37825970b92b90ddd50107d50a4cf922c/drac/drac_test.go#L65)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Prefer testing public interfaces whenever possible.

In this case, we could make Connect public, or only test Exec after wrapping `*ssh.Session` in an interface.
</blockquote></details>

I pretty radically changed the unit tests here:
- `dialer`, `client` and `session` are interfaces, to allow mocking
- `dialer.Dial` returns a `client` (instead of a `ssh.Client`)
- `client.NewSession` returns a `session` (instead of a `ssh.Session`)
- `session.CombinedOutput` returns pre-defined responses to the DRAC commands we are interested in

This way I can mock the whole dialer -> client -> session hierarchy in my tests and there's no external dependency on SSH anymore.

Most of the methods are now private, the only public ones are Exec and Reboot.

As we discussed on a call, returning interfaces is generally not a great idea in Go, since interfaces are normally defined by the consumer. In our case, though, those interfaces are purely internal to the package and not meant to be exposed in any way, thus I made them private.

I have considered running an SSH server to test this part, even if that would definitely blur the line between unit test and integration test. As an example, the ssh package's test suite itself spawns a server with a temporary configuration and runs some tests against that, using a Unix socket instead of creating a TCP connection.

However, mocking responses to commands would have been more complicated in that case and the utility functions in the SSH package's tests are all private.

What do you think of this solution?

**Review by stephen-soltesz — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/reboot-service/1)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @evfirerob and @stephen-soltesz)

___
*[README.md, line 14 at r2](https://reviewable.io/reviews/m-lab/reboot-service/1#-LZ_HZyg44c1JcRLbfvn:-LZ_HZyg44c1JcRLbfvo:b-3url6m) ([raw file](https://github.com/m-lab/reboot-service/blob/918ae1c85816cae8f7a5b2e3a9684df4579092f8/README.md#L14)):*
> ```Markdown
> - Execute commands on DRACs
> - Execute a reboot command
>     
> ```

nit: extra whitespaces.
___
*[README.md, line 17 at r2](https://reviewable.io/reviews/m-lab/reboot-service/1#-LZ_HcPY7BfeYncZl2rU:-LZ_HcPY7BfeYncZl2rV:bv8944i) ([raw file](https://github.com/m-lab/reboot-service/blob/918ae1c85816cae8f7a5b2e3a9684df4579092f8/README.md#L17)):*
> ```Markdown
> ### Things that do *NOT* work yet:
> - Send commands with more than 256 characters
> - SSH host key validation (currently skipped - **UNSAFE**)
> ```

vscode has settings to help prevent these things:

```
    "files.trimTrailingWhitespace": true,
    "files.insertFinalNewline": true,
```
___
*[drac/drac.go, line 25 at r2](https://reviewable.io/reviews/m-lab/reboot-service/1#-LZ_nPlVErfxx6IyNMuA:-LZ_nPlVErfxx6IyNMuB:b5twtj6) ([raw file](https://github.com/m-lab/reboot-service/blob/918ae1c85816cae8f7a5b2e3a9684df4579092f8/drac/drac.go#L25)):*
> ```Go
> 	Auth *ssh.ClientConfig
> 
> 	dialer  Dialer
> ```

I imagine these as nested objects. For example, a single client could in principle have multiple sessions open, right? I imagine only needing the dialer reference here. But there will also need to be simple ClientImpl and SessionImpl wrappers around the underlying ssh operations.
___
*[drac/drac.go, line 40 at r2](https://reviewable.io/reviews/m-lab/reboot-service/1#-LZ_ouwG7agDiZtEviKg:-LZ_nnXa28ee8Mnporl4:bc3m0az) ([raw file](https://github.com/m-lab/reboot-service/blob/918ae1c85816cae8f7a5b2e3a9684df4579092f8/drac/drac.go#L40)):*
> ```Go
> // Dial is just a wrapper around ssh.Dial
> func (d *DialerImpl) Dial(network, addr string,
> 	config *ssh.ClientConfig) (*ssh.Client, error) {
> ```

Does this implement the Dialer interface?

Adding compile-time checks like this one can be helpful. https://github.com/m-lab/go/blob/master/bytecount/bytes_test.go#L68
___
*[drac/drac.go, line 130 at r2](https://reviewable.io/reviews/m-lab/reboot-service/1#-LZ_mY11CIuy2IxQshlv:-LZ_mY11CIuy2IxQshlw:b-y4o3nf) ([raw file](https://github.com/m-lab/reboot-service/blob/918ae1c85816cae8f7a5b2e3a9684df4579092f8/drac/drac.go#L130)):*
> ```Go
> 		session, err := c.client.NewSession()
> 		if err != nil {
> 			log.Printf("Error while initializing SSH session: %s", err)
> ```

Should this error be returned?
___
*[drac/drac.go, line 161 at r2](https://reviewable.io/reviews/m-lab/reboot-service/1#-LZ_lmzl0e1dAmpM5Xd3:-LZ_lmzl0e1dAmpM5Xd4:bb6kdff) ([raw file](https://github.com/m-lab/reboot-service/blob/918ae1c85816cae8f7a5b2e3a9684df4579092f8/drac/drac.go#L161)):*
> ```Go
> // Exec executes a command on this Connection.
> func (c *Connection) Exec(cmd string) (string, error) {
> 	c.connect()
> ```

Please check all errors.
___
*[drac/drac_test.go, line 19 at r2](https://reviewable.io/reviews/m-lab/reboot-service/1#-LZ_o4UUEn9KwraWpyPX:-LZ_o4UUEn9KwraWpyPY:b-4fhtd2) ([raw file](https://github.com/m-lab/reboot-service/blob/918ae1c85816cae8f7a5b2e3a9684df4579092f8/drac/drac_test.go#L19)):*
> ```Go
> type mockDialer struct{}
> type mockClient struct{}
> type mockSession struct {
> ```

I imagine these objects being nested to mirror how the actual ssh package operates: a dialer contains a client, a client contains a session.

```
type mockDialer struct {
  Client
}
type mockClient {
  Session
}
```

**Review by robertodauria — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/reboot-service/1)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @evfirerob and @stephen-soltesz)

___
*[drac/drac.go, line 25 at r2](https://reviewable.io/reviews/m-lab/reboot-service/1#-LZ_nPlVErfxx6IyNMuA:-LZa6OaX6Phqoj7gwgjI:batsd8t) ([raw file](https://github.com/m-lab/reboot-service/blob/918ae1c85816cae8f7a5b2e3a9684df4579092f8/drac/drac.go#L25)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

I imagine these as nested objects. For example, a single client could in principle have multiple sessions open, right? I imagine only needing the dialer reference here. But there will also need to be simple ClientImpl and SessionImpl wrappers around the underlying ssh operations.
</blockquote></details>

It intuitively makes sense that a client keeps track of one or many sessions, but apparently ssh.Client does not store them. You can only get a new session but not previously created ones.
___
*[drac/drac.go, line 40 at r2](https://reviewable.io/reviews/m-lab/reboot-service/1#-LZ_ouwG7agDiZtEviKg:-LZ_vRgW1YSi7wjJQ6yD:b-l2bhi5) ([raw file](https://github.com/m-lab/reboot-service/blob/918ae1c85816cae8f7a5b2e3a9684df4579092f8/drac/drac.go#L40)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Does this implement the Dialer interface?

Adding compile-time checks like this one can be helpful. https://github.com/m-lab/go/blob/master/bytecount/bytes_test.go#L68
</blockquote></details>

Thanks! It slipped because that dialerImpl is meant to be used by the consumer (`main.go`, not in this PR). That test would have definitely highlighted the problem, I've added it now.
___
*[drac/drac.go, line 130 at r2](https://reviewable.io/reviews/m-lab/reboot-service/1#-LZ_mY11CIuy2IxQshlv:-LZ_vRF_8Mwqeb-DPBqD:b-896fix) ([raw file](https://github.com/m-lab/reboot-service/blob/918ae1c85816cae8f7a5b2e3a9684df4579092f8/drac/drac.go#L130)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Should this error be returned?
</blockquote></details>

Done.
___
*[drac/drac.go, line 161 at r2](https://reviewable.io/reviews/m-lab/reboot-service/1#-LZ_lmzl0e1dAmpM5Xd3:-LZ_vQkrDb2OZ1bNl6gY:b-896fix) ([raw file](https://github.com/m-lab/reboot-service/blob/918ae1c85816cae8f7a5b2e3a9684df4579092f8/drac/drac.go#L161)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Please check all errors.
</blockquote></details>

Done.
___
*[drac/drac_test.go, line 19 at r2](https://reviewable.io/reviews/m-lab/reboot-service/1#-LZ_o4UUEn9KwraWpyPX:-LZa7HVpBiHYZnIXFEoO:b-x56rzx) ([raw file](https://github.com/m-lab/reboot-service/blob/918ae1c85816cae8f7a5b2e3a9684df4579092f8/drac/drac_test.go#L19)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

I imagine these objects being nested to mirror how the actual ssh package operates: a dialer contains a client, a client contains a session.

```
type mockDialer struct {
  Client
}
type mockClient {
  Session
}
```
</blockquote></details>

`dialer` is basically mocking the package level (`ssh.Dial()` becomes `dialer.Dial`), it doesn't keep any reference to `client`. As above, `ssh.Client` doesn't seem to keep any references to `ssh.Session` types either. Maybe I am missing something here? https://github.com/golang/crypto/blob/master/ssh/client.go#L19

**Review by robertodauria — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/reboot-service/1)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @evfirerob and @stephen-soltesz)

___
*[README.md, line 17 at r2](https://reviewable.io/reviews/m-lab/reboot-service/1#-LZ_HcPY7BfeYncZl2rU:-LZaBjmy8GOvifVX4Bgx:boyexb3) ([raw file](https://github.com/m-lab/reboot-service/blob/918ae1c85816cae8f7a5b2e3a9684df4579092f8/README.md#L17)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

vscode has settings to help prevent these things:

```
    "files.trimTrailingWhitespace": true,
    "files.insertFinalNewline": true,
```
</blockquote></details>

Done. Thanks!

**Review by stephen-soltesz — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/reboot-service/1)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @evfirerob)

___
*[.travis.yml, line 9 at r3](https://reviewable.io/reviews/m-lab/reboot-service/1#-LZaCSZ5-zfwtWzaBJXN:-LZaCSZ5-zfwtWzaBJXO:b-19t3a9) ([raw file](https://github.com/m-lab/reboot-service/blob/edb396561ff266a365a8d0c768b0a2560590ef3d/.travis.yml#L9)):*
> ```YAML
> script:
> - go test -covermode=count -coverprofile=profile.cov ./...
> - goveralls -coverprofile=profile.cov -service=travis-ci
> ```

Is this working?

**Review by stephen-soltesz — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/m-lab/reboot-service/1#-:-LZaJBLUDoqEgxChp8MP:bnfp4nl)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @evfirerob)

**Pull request merged**
