### PR TITLE
Add HTTP basic authentication.

### PR DESCRIPTION
**Pull request by robertodauria**
This PR adds HTTP basic auth to the Reboot API.

Username and password are configurable through the command line flags `-auth.username` and `-auth.password` or the corresponding ENV variables.

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/reboot-service/9)

### CODE REVIEW

**Review by pboothe — COMMENTED** [review]
Can we update this to use `httpx.ServeTLSAsync` instead? It feel very wrong to send http auth tokens in plaintext.

> *[Reviewable](https://reviewable.io/reviews/m-lab/reboot-service/9#-:-Ld9qZzrCniKlSBBzJt0:bqy4c64)* status: 0 of 1 approvals obtained (waiting on @pboothe)

**Review by pboothe — COMMENTED** [review]
I mean `https.ListenAndServeTLSAsync`: https://github.com/m-lab/go/blob/master/httpx/httpx.go#L88

> *[Reviewable](https://reviewable.io/reviews/m-lab/reboot-service/9#-:-Ld9qlY06hGCvMse664V:blw421y)* status: 0 of 1 approvals obtained (waiting on @pboothe)

**Review by pboothe — APPROVED** [review]
After discussion, I found out the plan is to put a secure proxy in front of this service. :lgtm: 

> *[Reviewable](https://reviewable.io/reviews/m-lab/reboot-service/9#-:-Ld9znON6jeRctnTnkrK:b-8zcxxk)* status: :shipit: complete! 1 of 1 approvals obtained

**Comment by robertodauria** [comment]
@pboothe we are going to put this service behind nginx + LetsEncrypt and to give it a DNS name (same configuration as Prometheus/Grafana on GKE) so it won't be accessible over plain HTTP.

EDIT: nevermind, I didn't see your comment. Thanks!

**Comment by pboothe** [comment]
Ugh. Clicked the wrong thing.  Please ignore my "self-requested review"

**Review by stephen-soltesz — COMMENTED** [review]
Since we control the server code, have you considered using golang.org/x/crypto/acme/autocert to allocate a Lets Encrypt cert directly without the extra config and process for nginx?

> *[Reviewable](https://reviewable.io/reviews/m-lab/reboot-service/9#-:-LdA6Oi08uZoAICIpqw1:b3e23ad)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @pboothe)

**Comment by robertodauria** [comment]
I haven't, but it sounds like a much simpler alternative. I'll have a look at it. Thanks!

**Pull request merged**
